"""Fourth

Revision ID: 345c29220a3e
Revises: 722af0d2e7df
Create Date: 2023-01-17 20:01:20.593267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345c29220a3e'
down_revision = '722af0d2e7df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('БЛЮДА', sa.Column('submenu', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'БЛЮДА', 'Подменю', ['submenu'], ['id'])
    op.add_column('Подменю', sa.Column('menu', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'Подменю', 'Меню', ['menu'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Подменю', type_='foreignkey')
    op.drop_column('Подменю', 'menu')
    op.drop_constraint(None, 'БЛЮДА', type_='foreignkey')
    op.drop_column('БЛЮДА', 'submenu')
    # ### end Alembic commands ###
