"""Second

Revision ID: e27340051a85
Revises: e3d8732ab8f2
Create Date: 2023-01-17 19:17:12.445110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e27340051a85'
down_revision = 'e3d8732ab8f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('БЛЮДА',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('cooking_time', sa.INTEGER(), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_БЛЮДА_id'), 'БЛЮДА', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_БЛЮДА_id'), table_name='БЛЮДА')
    op.drop_table('БЛЮДА')
    # ### end Alembic commands ###
